# Generated by Django 3.2.7 on 2023-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('symptom', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=200)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=130)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=230)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
